// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using questionario_tcc_api.Data;

#nullable disable

namespace questionario_tcc_api.Migrations
{
    [DbContext(typeof(RegistroDePacientesDbContext))]
    [Migration("20230421151549_questionario_Db_docker")]
    partial class questionario_Db_docker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("questionario_tcc_api.Models.PacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnosCafeleia")
                        .HasColumnType("int");

                    b.Property<bool>("Bebida")
                        .HasColumnType("bit");

                    b.Property<int>("BedidasSemana")
                        .HasColumnType("int");

                    b.Property<bool>("BuscaProficional")
                        .HasColumnType("bit");

                    b.Property<string>("DiscriçãoDor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoencaCronica")
                        .HasColumnType("bit");

                    b.Property<int>("DorAtividadeGeral")
                        .HasColumnType("int");

                    b.Property<int>("DorHumor")
                        .HasColumnType("int");

                    b.Property<bool>("DorIrradia")
                        .HasColumnType("bit");

                    b.Property<int>("DorLocomocao")
                        .HasColumnType("int");

                    b.Property<int>("DorMomento")
                        .HasColumnType("int");

                    b.Property<int>("DorRelacionamento")
                        .HasColumnType("int");

                    b.Property<int>("DorSono")
                        .HasColumnType("int");

                    b.Property<int>("DorTrabalho")
                        .HasColumnType("int");

                    b.Property<int>("DorVida")
                        .HasColumnType("int");

                    b.Property<int>("EpisodiosMes")
                        .HasColumnType("int");

                    b.Property<int>("Etnia")
                        .HasColumnType("int");

                    b.Property<bool>("FatorAgravante")
                        .HasColumnType("bit");

                    b.Property<bool>("FatorAtenuante")
                        .HasColumnType("bit");

                    b.Property<bool>("Fuma")
                        .HasColumnType("bit");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<int>("GeralDor24h")
                        .HasColumnType("int");

                    b.Property<int>("HoraExercicio")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<int>("ItensidadeDor")
                        .HasColumnType("int");

                    b.Property<double>("LocalDorX")
                        .HasColumnType("float");

                    b.Property<double>("LocalDorY")
                        .HasColumnType("float");

                    b.Property<int>("LocalExataDor")
                        .HasColumnType("int");

                    b.Property<double>("LocalIrradiaDorX")
                        .HasColumnType("float");

                    b.Property<double>("LocalIrradiaDorY")
                        .HasColumnType("float");

                    b.Property<double>("LocalMaiorDorX")
                        .HasColumnType("float");

                    b.Property<double>("LocalMaiorDorY")
                        .HasColumnType("float");

                    b.Property<int>("MaiorDor24h")
                        .HasColumnType("int");

                    b.Property<bool>("MedicamentoContinuo")
                        .HasColumnType("bit");

                    b.Property<bool>("Melhora")
                        .HasColumnType("bit");

                    b.Property<int>("MenorDor24h")
                        .HasColumnType("int");

                    b.Property<int>("MlCafeSemana")
                        .HasColumnType("int");

                    b.Property<int>("QtdMacosSemana")
                        .HasColumnType("int");

                    b.Property<string>("QualDoenca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualFatorAgravante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualFatorAtenuante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualMedicamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualSintomasAlem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SintomasAlem")
                        .HasColumnType("bit");

                    b.Property<int>("StatusCivil")
                        .HasColumnType("int");

                    b.Property<string>("TempoCrise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempoPicoDor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TratamentoDor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
